using System;

namespace UttrekkFamilia.Models
{
    public partial class FaEier
    {
        public decimal KomKommunenr { get; set; }
        public string PnrPostnr { get; set; }
        public string EieEtat { get; set; }
        public string EieAdresse1 { get; set; }
        public string EieAdresse2 { get; set; }
        public string EieTelefonnr { get; set; }
        public string EieTelefaksnr { get; set; }
        public decimal? EieFolketall { get; set; }
        public string EieMaalform { get; set; }
        public string EieKontrollnivaavedtak { get; set; }
        public decimal EieTillaterKnv0 { get; set; }
        public decimal EieTillaterKnv1 { get; set; }
        public decimal EieTillaterKnv2 { get; set; }
        public decimal EieKntrlvedtakAnnensbh { get; set; }
        public decimal EieKreveklargjoersak { get; set; }
        public decimal EieKrevedistrikt { get; set; }
        public decimal EieKkoder { get; set; }
        public decimal EieHindrekopiutskrift { get; set; }
        public decimal EieOblUndersoekplan { get; set; }
        public decimal? EieAntdgUndersoekfrist { get; set; }
        public decimal? EieAntdgUtloepUtbplan { get; set; }
        public decimal? EieAngrefristinnbetaling { get; set; }
        public decimal? EieAngrefristutbetaling { get; set; }
        public decimal? EieAngrefristvedtak { get; set; }
        public decimal? EieAngrfristjournalnotat { get; set; }
        public decimal? EieLoggdoegn { get; set; }
        public decimal? EieGyldighetpassord { get; set; }
        public decimal? EieMinstealder { get; set; }
        public decimal? EieMaksalder { get; set; }
        public decimal? EieVedtakvarighet { get; set; }
        public string EieVilkaarbehandling { get; set; }
        public string EieUtbetalingMandag { get; set; }
        public string EieUtbetalingTirsdag { get; set; }
        public string EieUtbetalingOnsdag { get; set; }
        public string EieUtbetalingTorsdag { get; set; }
        public string EieUtbetalingFredag { get; set; }
        public string EieUtbetalingLoerdag { get; set; }
        public string EieUtbetalingSoendag { get; set; }
        public decimal EieSsbKrevefelt { get; set; }
        public string EieSsbProgram { get; set; }
        public string EieSsbTeksteditor { get; set; }
        public string EieRemSystem { get; set; }
        public string EieRemSti { get; set; }
        public string EieRemDatovalg { get; set; }
        public string EieRemOppdragskonto { get; set; }
        public DateTime? EieRemSistedato { get; set; }
        public string EieRemSisteprodnridag { get; set; }
        public string EieBbsAvtaleid { get; set; }
        public string EieBbsKundeid { get; set; }
        public string EieRgnSystem { get; set; }
        public string EieRgnForsystem { get; set; }
        public string EieRgnFirma { get; set; }
        public string EieRgnAggregeringsnivaa { get; set; }
        public string EieRgnSti { get; set; }
        public string EieStiFolkeregister { get; set; }
        public string EieStiRutinehandbok { get; set; }
        public string EieLnnSystem { get; set; }
        public string EieLnnKundeid { get; set; }
        public string EieLnnSti { get; set; }
        public string EieOrganisasjonsnr { get; set; }
        public string EieKtoArbgiveravg { get; set; }
        public string EieKtoFeriepenger { get; set; }
        public string EieKtoArbgiverferie { get; set; }
        public decimal? EieAntdgVarselmelding { get; set; }
        public decimal? EieAntdgVarseltiltak { get; set; }
        public decimal? EieAntdgVarselundersoekelse { get; set; }
        public decimal EieDokEttDok { get; set; }
        public decimal EieInngFerdigIns { get; set; }
        public decimal EieAutomatiskDoklistenr { get; set; }
        public string EieKontonr { get; set; }
        public decimal? EieMaxSjekkKopier { get; set; }
        public DateTime? EiePer01 { get; set; }
        public DateTime? EiePer02 { get; set; }
        public DateTime? EiePer03 { get; set; }
        public DateTime? EiePer04 { get; set; }
        public DateTime? EiePer05 { get; set; }
        public DateTime? EiePer06 { get; set; }
        public DateTime? EiePer07 { get; set; }
        public DateTime? EiePer08 { get; set; }
        public DateTime? EiePer09 { get; set; }
        public DateTime? EiePer10 { get; set; }
        public DateTime? EiePer11 { get; set; }
        public DateTime? EiePer12 { get; set; }
        public decimal? EieRemKundenr { get; set; }
        public string EieRemSistesekvnrAvtale { get; set; }
        public string EieRgnBilagsart { get; set; }
        public string EieRgnAggregerMotpost { get; set; }
        public decimal EieVarsleegenbet { get; set; }
        public decimal EieGodkjennutenvurd { get; set; }
        public string EieBydelsnr { get; set; }
        public string EieRemDivisjon { get; set; }
        public decimal EieKopiklientmeldinger { get; set; }
        public string EieBalanseArbgiveravg { get; set; }
        public string EieBalanseFeriepenger { get; set; }
        public string EieBalanseArbgiverferie { get; set; }
        public decimal EieRgnUtvidetFilnavn { get; set; }
        public decimal EieRemKassabilag { get; set; }
        public decimal EiePassivInternavregning { get; set; }
        public decimal EiePassivInternfakturering { get; set; }
        public string EieFolkregUrl { get; set; }
        public string EieFolkregBruker { get; set; }
        public string EieFolkregPassord { get; set; }
        public string EieRgnFiltype { get; set; }
        public decimal EieAutomatiskBilag { get; set; }
        public decimal EieAutomatiskRemfil { get; set; }
        public decimal EieAutomatiskLoenn { get; set; }
        public decimal EieEngAutoPlangodkjenning { get; set; }
        public decimal EieEngFortloepende { get; set; }
        public decimal EieEngKravPlangodkjenning { get; set; }
        public string EieRgnMvakode { get; set; }
        public string EieRegnskapProgsrv { get; set; }
        public string EieRegnskapSystem { get; set; }
        public decimal? EieRegnskapPort { get; set; }
        public string EieRegnskapUserid { get; set; }
        public string EieRegnskapPassord { get; set; }
        public string EieLevregDblinkServer { get; set; }
        public string EieLevregDblinkDb { get; set; }
        public string EieLevregBruker { get; set; }
        public string EieLevregPassord { get; set; }
        public string EieRemRet { get; set; }
        public string EieEkstLnnType { get; set; }
        public string EieEkstLnnBrukerid { get; set; }
        public string EieEkstLnnPassord { get; set; }
        public string EieEkstLnnHovedsystem { get; set; }
        public string EieEkstLnnIntegrertsystem { get; set; }
        public string EieEkstLnnBrukernr { get; set; }
        public string EieEkstLnnBilagsformat { get; set; }
        public DateTime? EieEkstLnnPassordendret { get; set; }
        public decimal? EieEkstLnnPassordvarighet { get; set; }
        public string EieEkstLnnUrl { get; set; }
        public string EieTypeFullformat { get; set; }
        public decimal EieDistriktsvisParametre { get; set; }
        public decimal EieKontofTiltak { get; set; }
        public decimal? EieAntdgVarselengavtale { get; set; }
        public decimal EieUndVeiviser { get; set; }
        public decimal? EieAngrefristPlan { get; set; }
        public string EieEkstUbUrl { get; set; }
        public string EieEkstVaUrl { get; set; }
        public string EieAktiverAvvikslogg { get; set; }
        public string EieProxyUrl { get; set; }
        public decimal ArkAktivert { get; set; }
        public DateTime? ArkFradato { get; set; }
        public DateTime? ArkTildato { get; set; }
        public string ArkStatus { get; set; }
        public decimal? EieAngrefristPostjournal { get; set; }
        public decimal? EieAngrefristjournalnotat { get; set; }
        public string EieVismaOkoSelskap { get; set; }
        public string EieVismaOkoRegion { get; set; }
        public string EieVismaOkoBruker { get; set; }
        public string EieVismaOkoPassord { get; set; }
        public string EieVismaOkoUrl { get; set; }
        public decimal EieVedtakUTildato { get; set; }
        public decimal EieKrevePjdokInn { get; set; }
        public decimal EieNotDoknrJournal { get; set; }
        public decimal? EieAngrefristEvaluering { get; set; }
        public decimal? EieAngrefristUndersoekPlan { get; set; }
        public decimal? EieAngrfrUndersoekSlutrapp { get; set; }
        public decimal? EieAngrefristGjennomgangsdok { get; set; }
        public decimal EieDigitalpost { get; set; }
        public decimal EieDigitalprint { get; set; }
        public decimal EiePostjApprovalMandatory { get; set; }
        public decimal EieBetalingIkkeregnskap { get; set; }
        public decimal EieUseCkEditor { get; set; }
        public decimal EieUseImportDistricts { get; set; }
        public string EieCkFontFamilyN { get; set; }
        public string EieCkFontSizeN { get; set; }
        public string EieCkFontFamilyH1 { get; set; }
        public string EieCkFontSizeH1 { get; set; }
        public string EieCkFontFamilyH2 { get; set; }
        public string EieCkFontSizeH2 { get; set; }
        public string EieCkFontFamilyH3 { get; set; }
        public string EieCkFontSizeH3 { get; set; }
        public string EieCkFontFamilyF { get; set; }
        public string EieCkFontSizeF { get; set; }
        public decimal EieFamiliekopiering { get; set; }
        public decimal EieSvarinnActive { get; set; }
        public DateTime? EieSvarinnFradato { get; set; }
        public DateTime? EieSvarinnTildato { get; set; }
        public string EieFlytOrganisasjonsnr { get; set; }
        public string EieFlytIntegrasjonsnokkel { get; set; }
        public string EieFlytUrl { get; set; }
        public decimal EieUnderSluttrappMandatory { get; set; }
        public decimal EieFolkregTls12 { get; set; }

        public virtual FaKommuner KomKommunenrNavigation { get; set; }
        public virtual FaPostadresser PnrPostnrNavigation { get; set; }
    }
}
