using System;

namespace UttrekkFamilia.Models
{
    public partial class FaStatTabell242
    {
        public DateTime D242PeriodeStartdato { get; set; }
        public DateTime D242PeriodeSluttdato { get; set; }
        public decimal KliLoepenr { get; set; }
        public string D242Distrikter { get; set; }
        public decimal? D242Innvandrer { get; set; }
        public decimal? D242Punkt1A { get; set; }
        public decimal? D242Punkt1B { get; set; }
        public decimal? D242Punkt1C { get; set; }
        public decimal? D242Punkt1D { get; set; }
        public decimal? D242Punkt1Pr { get; set; }
        public decimal? D242Punkt1Hel { get; set; }
        public decimal? D242Punkt1Fly { get; set; }
        public decimal? D242Punkt1aPr { get; set; }
        public decimal? D242Punkt1aHel { get; set; }
        public decimal? D242Punkt1aFly { get; set; }
        public decimal? D242Punkt11A { get; set; }
        public decimal? D242Punkt11B { get; set; }
        public decimal? D242Punkt11C { get; set; }
        public decimal? D242Punkt11D { get; set; }
        public decimal? D242Punkt11Pr { get; set; }
        public decimal? D242Punkt11Hel { get; set; }
        public decimal? D242Punkt11Fly { get; set; }
        public decimal? D242Punkt11iA { get; set; }
        public decimal? D242Punkt11iB { get; set; }
        public decimal? D242Punkt11iC { get; set; }
        public decimal? D242Punkt11iD { get; set; }
        public decimal? D242Punkt11iPr { get; set; }
        public decimal? D242Punkt11iHel { get; set; }
        public decimal? D242Punkt11iFly { get; set; }
        public decimal? D242Punkt111A { get; set; }
        public decimal? D242Punkt111B { get; set; }
        public decimal? D242Punkt111C { get; set; }
        public decimal? D242Punkt111D { get; set; }
        public decimal? D242Punkt111Pr { get; set; }
        public decimal? D242Punkt111Hel { get; set; }
        public decimal? D242Punkt111Fly { get; set; }
        public decimal? D242Punkt111iA { get; set; }
        public decimal? D242Punkt111iB { get; set; }
        public decimal? D242Punkt111iC { get; set; }
        public decimal? D242Punkt111iD { get; set; }
        public decimal? D242Punkt111iPr { get; set; }
        public decimal? D242Punkt111iHel { get; set; }
        public decimal? D242Punkt111iFly { get; set; }
        public decimal? D242Punkt112A { get; set; }
        public decimal? D242Punkt112B { get; set; }
        public decimal? D242Punkt112C { get; set; }
        public decimal? D242Punkt112D { get; set; }
        public decimal? D242Punkt112Pr { get; set; }
        public decimal? D242Punkt112Hel { get; set; }
        public decimal? D242Punkt112Fly { get; set; }
        public decimal? D242Punkt112iA { get; set; }
        public decimal? D242Punkt112iB { get; set; }
        public decimal? D242Punkt112iC { get; set; }
        public decimal? D242Punkt112iD { get; set; }
        public decimal? D242Punkt112iPr { get; set; }
        public decimal? D242Punkt112iHel { get; set; }
        public decimal? D242Punkt112iFly { get; set; }
        public decimal? D242Punkt12A { get; set; }
        public decimal? D242Punkt12B { get; set; }
        public decimal? D242Punkt12C { get; set; }
        public decimal? D242Punkt12D { get; set; }
        public decimal? D242Punkt12Pr { get; set; }
        public decimal? D242Punkt12Hel { get; set; }
        public decimal? D242Punkt12Fly { get; set; }
        public decimal? D242Punkt12iA { get; set; }
        public decimal? D242Punkt12iB { get; set; }
        public decimal? D242Punkt12iC { get; set; }
        public decimal? D242Punkt12iD { get; set; }
        public decimal? D242Punkt12iPr { get; set; }
        public decimal? D242Punkt12iHel { get; set; }
        public decimal? D242Punkt12iFly { get; set; }
        public decimal? D242Punkt13A { get; set; }
        public decimal? D242Punkt13B { get; set; }
        public decimal? D242Punkt13C { get; set; }
        public decimal? D242Punkt13D { get; set; }
        public decimal? D242Punkt13Pr { get; set; }
        public decimal? D242Punkt13Hel { get; set; }
        public decimal? D242Punkt13Fly { get; set; }
        public decimal? D242Punkt13iA { get; set; }
        public decimal? D242Punkt13iB { get; set; }
        public decimal? D242Punkt13iC { get; set; }
        public decimal? D242Punkt13iD { get; set; }
        public decimal? D242Punkt13iPr { get; set; }
        public decimal? D242Punkt13iHel { get; set; }
        public decimal? D242Punkt13iFly { get; set; }
        public decimal? D242Punkt14A { get; set; }
        public decimal? D242Punkt14B { get; set; }
        public decimal? D242Punkt14C { get; set; }
        public decimal? D242Punkt14D { get; set; }
        public decimal? D242Punkt14Pr { get; set; }
        public decimal? D242Punkt14Hel { get; set; }
        public decimal? D242Punkt14Fly { get; set; }
        public decimal? D242Punkt14iA { get; set; }
        public decimal? D242Punkt14iB { get; set; }
        public decimal? D242Punkt14iC { get; set; }
        public decimal? D242Punkt14iD { get; set; }
        public decimal? D242Punkt14iPr { get; set; }
        public decimal? D242Punkt14iHel { get; set; }
        public decimal? D242Punkt14iFly { get; set; }
        public decimal? D242Punkt15A { get; set; }
        public decimal? D242Punkt15B { get; set; }
        public decimal? D242Punkt15C { get; set; }
        public decimal? D242Punkt15D { get; set; }
        public decimal? D242Punkt15Pr { get; set; }
        public decimal? D242Punkt15Hel { get; set; }
        public decimal? D242Punkt15Fly { get; set; }
        public decimal? D242Punkt15iA { get; set; }
        public decimal? D242Punkt15iB { get; set; }
        public decimal? D242Punkt15iC { get; set; }
        public decimal? D242Punkt15iD { get; set; }
        public decimal? D242Punkt15iPr { get; set; }
        public decimal? D242Punkt15iHel { get; set; }
        public decimal? D242Punkt15iFly { get; set; }
        public decimal? D242Punkt16A { get; set; }
        public decimal? D242Punkt16B { get; set; }
        public decimal? D242Punkt16C { get; set; }
        public decimal? D242Punkt16D { get; set; }
        public decimal? D242Punkt16Pr { get; set; }
        public decimal? D242Punkt16Hel { get; set; }
        public decimal? D242Punkt16Fly { get; set; }
        public decimal? D242Punkt16iA { get; set; }
        public decimal? D242Punkt16iB { get; set; }
        public decimal? D242Punkt16iC { get; set; }
        public decimal? D242Punkt16iD { get; set; }
        public decimal? D242Punkt16iPr { get; set; }
        public decimal? D242Punkt16iHel { get; set; }
        public decimal? D242Punkt16iFly { get; set; }
        public decimal? D242bPunkt1Hel { get; set; }
        public decimal? D242bPunkt11Hel { get; set; }
        public decimal? D242bPunkt11Fly { get; set; }
        public string D242Klientgrupper { get; set; }
        public string D242Saksbehandlere { get; set; }
        public string D242Distriktsnavn { get; set; }
    }
}
