using System;

namespace UttrekkFamilia.Models
{
    public partial class FaStatSsb1
    {
        public decimal KliLoepenr { get; set; }
        public string Ss1Periode { get; set; }
        public string DisDistriktskode { get; set; }
        public string Ss1Fodselsnr { get; set; }
        public DateTime? Ss1Startdatoundersokelse { get; set; }
        public DateTime? Ss1Sluttdatoundersokelse { get; set; }
        public decimal? Ss1Sakenmeldtav01 { get; set; }
        public decimal? Ss1Sakenmeldtav02 { get; set; }
        public decimal? Ss1Sakenmeldtav03 { get; set; }
        public decimal? Ss1Sakenmeldtav04 { get; set; }
        public decimal? Ss1Sakenmeldtav05 { get; set; }
        public decimal? Ss1Sakenmeldtav06 { get; set; }
        public decimal? Ss1Sakenmeldtav07 { get; set; }
        public decimal? Ss1Sakenmeldtav08 { get; set; }
        public decimal? Ss1Sakenmeldtav09 { get; set; }
        public decimal? Ss1Sakenmeldtav10 { get; set; }
        public decimal? Ss1Sakenmeldtav11 { get; set; }
        public decimal? Ss1Sakenmeldtav12 { get; set; }
        public decimal? Ss1Sakenmeldtav13 { get; set; }
        public decimal? Ss1Sakenmeldtav14 { get; set; }
        public decimal? Ss1Sakenmeldtav15 { get; set; }
        public decimal? Ss1Sakenmeldtav16 { get; set; }
        public decimal? Ss1Sakenmeldtav17 { get; set; }
        public decimal? Ss1Sakenmeldtav18 { get; set; }
        public decimal? Ss1Sakenmeldtav19 { get; set; }
        public decimal? Ss1Sakenmeldtav20 { get; set; }
        public decimal? Ss1Saksinnhold01 { get; set; }
        public decimal? Ss1Saksinnhold02 { get; set; }
        public decimal? Ss1Saksinnhold03 { get; set; }
        public decimal? Ss1Saksinnhold04 { get; set; }
        public decimal? Ss1Antallundersokelser { get; set; }
        public string Ss1Resultatvedtak { get; set; }
        public DateTime? Ss1Resultatvedtakdato { get; set; }
        public string Ss1Resultathenlagt { get; set; }
        public DateTime? Ss1Resultathenlagtdato { get; set; }
        public decimal? Ss1Resultatikkeavsluttet { get; set; }
        public string Ss1Tidligeretiltak { get; set; }
        public string Ss1Typeforstetiltak { get; set; }
        public decimal? Ss1Undersokelseintlopenr { get; set; }
        public decimal? Ss1SakJournalnr { get; set; }
        public decimal? Ss1SakAar { get; set; }
        public string Ss1MynVedtakstype { get; set; }
        public string Ss1Tiltak01typetiltakh { get; set; }
        public string Ss1Tiltak01typetiltako { get; set; }
        public string Ss1Tiltak01lovgrunnlag1 { get; set; }
        public string Ss1Tiltak01lovgrunnlag2 { get; set; }
        public string Ss1Tiltak01tidlmnd { get; set; }
        public string Ss1Tiltak01tidlaar { get; set; }
        public string Ss1Tiltak01antmnd { get; set; }
        public string Ss1Tiltak02typetiltakh { get; set; }
        public string Ss1Tiltak02typetiltako { get; set; }
        public string Ss1Tiltak02lovgrunnlag1 { get; set; }
        public string Ss1Tiltak02lovgrunnlag2 { get; set; }
        public string Ss1Tiltak02tidlmnd { get; set; }
        public string Ss1Tiltak02tidlaar { get; set; }
        public string Ss1Tiltak02antmnd { get; set; }
        public string Ss1Tiltak03typetiltakh { get; set; }
        public string Ss1Tiltak03typetiltako { get; set; }
        public string Ss1Tiltak03lovgrunnlag1 { get; set; }
        public string Ss1Tiltak03lovgrunnlag2 { get; set; }
        public string Ss1Tiltak03tidlmnd { get; set; }
        public string Ss1Tiltak03tidlaar { get; set; }
        public string Ss1Tiltak03antmnd { get; set; }
        public string Ss1Tiltak04typetiltakh { get; set; }
        public string Ss1Tiltak04typetiltako { get; set; }
        public string Ss1Tiltak04lovgrunnlag1 { get; set; }
        public string Ss1Tiltak04lovgrunnlag2 { get; set; }
        public string Ss1Tiltak04tidlmnd { get; set; }
        public string Ss1Tiltak04tidlaar { get; set; }
        public string Ss1Tiltak04antmnd { get; set; }
        public string Ss1Tiltak05typetiltakh { get; set; }
        public string Ss1Tiltak05typetiltako { get; set; }
        public string Ss1Tiltak05lovgrunnlag1 { get; set; }
        public string Ss1Tiltak05lovgrunnlag2 { get; set; }
        public string Ss1Tiltak05tidlmnd { get; set; }
        public string Ss1Tiltak05tidlaar { get; set; }
        public string Ss1Tiltak05antmnd { get; set; }
        public string Ss1Tiltak06typetiltakh { get; set; }
        public string Ss1Tiltak06typetiltako { get; set; }
        public string Ss1Tiltak06lovgrunnlag1 { get; set; }
        public string Ss1Tiltak06lovgrunnlag2 { get; set; }
        public string Ss1Tiltak06tidlmnd { get; set; }
        public string Ss1Tiltak06tidlaar { get; set; }
        public string Ss1Tiltak06antmnd { get; set; }
        public string Ss1Tiltak07typetiltakh { get; set; }
        public string Ss1Tiltak07typetiltako { get; set; }
        public string Ss1Tiltak07lovgrunnlag1 { get; set; }
        public string Ss1Tiltak07lovgrunnlag2 { get; set; }
        public string Ss1Tiltak07tidlmnd { get; set; }
        public string Ss1Tiltak07tidlaar { get; set; }
        public string Ss1Tiltak07antmnd { get; set; }
        public string Ss1Tiltak08typetiltakh { get; set; }
        public string Ss1Tiltak08typetiltako { get; set; }
        public string Ss1Tiltak08lovgrunnlag1 { get; set; }
        public string Ss1Tiltak08lovgrunnlag2 { get; set; }
        public string Ss1Tiltak08tidlmnd { get; set; }
        public string Ss1Tiltak08tidlaar { get; set; }
        public string Ss1Tiltak08antmnd { get; set; }
        public string Ss1Tiltak09typetiltakh { get; set; }
        public string Ss1Tiltak09typetiltako { get; set; }
        public string Ss1Tiltak09lovgrunnlag1 { get; set; }
        public string Ss1Tiltak09lovgrunnlag2 { get; set; }
        public string Ss1Tiltak09tidlmnd { get; set; }
        public string Ss1Tiltak09tidlaar { get; set; }
        public string Ss1Tiltak09antmnd { get; set; }
        public string Ss1Tiltak10typetiltakh { get; set; }
        public string Ss1Tiltak10typetiltako { get; set; }
        public string Ss1Tiltak10lovgrunnlag1 { get; set; }
        public string Ss1Tiltak10lovgrunnlag2 { get; set; }
        public string Ss1Tiltak10tidlmnd { get; set; }
        public string Ss1Tiltak10tidlaar { get; set; }
        public string Ss1Tiltak10antmnd { get; set; }
        public string Ss1Tiltak11typetiltakh { get; set; }
        public string Ss1Tiltak11typetiltako { get; set; }
        public string Ss1Tiltak11lovgrunnlag1 { get; set; }
        public string Ss1Tiltak11lovgrunnlag2 { get; set; }
        public string Ss1Tiltak11tidlmnd { get; set; }
        public string Ss1Tiltak11tidlaar { get; set; }
        public string Ss1Tiltak11antmnd { get; set; }
        public string Ss1Tiltak12typetiltakh { get; set; }
        public string Ss1Tiltak12typetiltako { get; set; }
        public string Ss1Tiltak12lovgrunnlag1 { get; set; }
        public string Ss1Tiltak12lovgrunnlag2 { get; set; }
        public string Ss1Tiltak12tidlmnd { get; set; }
        public string Ss1Tiltak12tidlaar { get; set; }
        public string Ss1Tiltak12antmnd { get; set; }
        public string Ss1Tiltak13typetiltakh { get; set; }
        public string Ss1Tiltak13typetiltako { get; set; }
        public string Ss1Tiltak13lovgrunnlag1 { get; set; }
        public string Ss1Tiltak13lovgrunnlag2 { get; set; }
        public string Ss1Tiltak13tidlmnd { get; set; }
        public string Ss1Tiltak13tidlaar { get; set; }
        public string Ss1Tiltak13antmnd { get; set; }
        public string Ss1Tiltak14typetiltakh { get; set; }
        public string Ss1Tiltak14typetiltako { get; set; }
        public string Ss1Tiltak14lovgrunnlag1 { get; set; }
        public string Ss1Tiltak14lovgrunnlag2 { get; set; }
        public string Ss1Tiltak14tidlmnd { get; set; }
        public string Ss1Tiltak14tidlaar { get; set; }
        public string Ss1Tiltak14antmnd { get; set; }
        public string Ss1Tiltak15typetiltakh { get; set; }
        public string Ss1Tiltak15typetiltako { get; set; }
        public string Ss1Tiltak15lovgrunnlag1 { get; set; }
        public string Ss1Tiltak15lovgrunnlag2 { get; set; }
        public string Ss1Tiltak15tidlmnd { get; set; }
        public string Ss1Tiltak15tidlaar { get; set; }
        public string Ss1Tiltak15antmnd { get; set; }
        public string Ss1Tiltak16typetiltakh { get; set; }
        public string Ss1Tiltak16typetiltako { get; set; }
        public string Ss1Tiltak16lovgrunnlag1 { get; set; }
        public string Ss1Tiltak16lovgrunnlag2 { get; set; }
        public string Ss1Tiltak16tidlmnd { get; set; }
        public string Ss1Tiltak16tidlaar { get; set; }
        public string Ss1Tiltak16antmnd { get; set; }
        public string Ss1Tiltak17typetiltakh { get; set; }
        public string Ss1Tiltak17typetiltako { get; set; }
        public string Ss1Tiltak17lovgrunnlag1 { get; set; }
        public string Ss1Tiltak17lovgrunnlag2 { get; set; }
        public string Ss1Tiltak17tidlmnd { get; set; }
        public string Ss1Tiltak17tidlaar { get; set; }
        public string Ss1Tiltak17antmnd { get; set; }
        public string Ss1Tiltak18typetiltakh { get; set; }
        public string Ss1Tiltak18typetiltako { get; set; }
        public string Ss1Tiltak18lovgrunnlag1 { get; set; }
        public string Ss1Tiltak18lovgrunnlag2 { get; set; }
        public string Ss1Tiltak18tidlmnd { get; set; }
        public string Ss1Tiltak18tidlaar { get; set; }
        public string Ss1Tiltak18antmnd { get; set; }
        public string Ss1Tiltak19typetiltakh { get; set; }
        public string Ss1Tiltak19typetiltako { get; set; }
        public string Ss1Tiltak19lovgrunnlag1 { get; set; }
        public string Ss1Tiltak19lovgrunnlag2 { get; set; }
        public string Ss1Tiltak19tidlmnd { get; set; }
        public string Ss1Tiltak19tidlaar { get; set; }
        public string Ss1Tiltak19antmnd { get; set; }
        public string Ss1Tiltak20typetiltakh { get; set; }
        public string Ss1Tiltak20typetiltako { get; set; }
        public string Ss1Tiltak20lovgrunnlag1 { get; set; }
        public string Ss1Tiltak20lovgrunnlag2 { get; set; }
        public string Ss1Tiltak20tidlmnd { get; set; }
        public string Ss1Tiltak20tidlaar { get; set; }
        public string Ss1Tiltak20antmnd { get; set; }
        public string Ss1Tiltak21typetiltakh { get; set; }
        public string Ss1Tiltak21typetiltako { get; set; }
        public string Ss1Tiltak21lovgrunnlag1 { get; set; }
        public string Ss1Tiltak21lovgrunnlag2 { get; set; }
        public string Ss1Tiltak21tidlmnd { get; set; }
        public string Ss1Tiltak21tidlaar { get; set; }
        public string Ss1Tiltak21antmnd { get; set; }
        public string Ss1Tiltak22typetiltakh { get; set; }
        public string Ss1Tiltak22typetiltako { get; set; }
        public string Ss1Tiltak22lovgrunnlag1 { get; set; }
        public string Ss1Tiltak22lovgrunnlag2 { get; set; }
        public string Ss1Tiltak22tidlmnd { get; set; }
        public string Ss1Tiltak22tidlaar { get; set; }
        public string Ss1Tiltak22antmnd { get; set; }
        public string Ss1Tiltak23typetiltakh { get; set; }
        public string Ss1Tiltak23typetiltako { get; set; }
        public string Ss1Tiltak23lovgrunnlag1 { get; set; }
        public string Ss1Tiltak23lovgrunnlag2 { get; set; }
        public string Ss1Tiltak23tidlmnd { get; set; }
        public string Ss1Tiltak23tidlaar { get; set; }
        public string Ss1Tiltak23antmnd { get; set; }
        public decimal? Ss1Fratattforeldreansvar { get; set; }
        public decimal? Ss1Grunnlagforvedtaket01 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket02 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket03 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket04 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket05 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket06 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket07 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket08 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket09 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket10 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket11 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket12 { get; set; }
        public decimal? Ss1Grunnlagforvedtaket13 { get; set; }
        public string Ss1Viktigstegrunnlag { get; set; }
        public string Ss1Barnetsstatsborgerskap { get; set; }
        public decimal? Ss1Morsfodeland { get; set; }
        public decimal? Ss1Farsfodeland { get; set; }
        public decimal? KomKommunenr { get; set; }

        public virtual FaKlient KliLoepenrNavigation { get; set; }
        public virtual FaKommuner KomKommunenrNavigation { get; set; }
        public virtual FaStatSsb2 FaStatSsb2 { get; set; }
    }
}
