namespace UttrekkFamilia.Models
{
    public partial class FaStatSsb2
    {
        public decimal KliLoepenr { get; set; }
        public string Ss1Periode { get; set; }
        public string DisDistriktskode { get; set; }
        public decimal? Ss2Punkt141 { get; set; }
        public decimal? Ss2Punkt142 { get; set; }
        public decimal? Ss2Punkt143 { get; set; }
        public decimal? Ss2Punkt144 { get; set; }
        public decimal? Ss2Punkt145 { get; set; }
        public decimal? Ss2Punkt146 { get; set; }
        public decimal? Ss2Punkt147 { get; set; }
        public decimal? Ss2Punkt148 { get; set; }
        public decimal? Ss2Punkt149 { get; set; }
        public decimal? Ss2Punkt1410 { get; set; }
        public decimal? Ss2Grunnlagforvedtaket14 { get; set; }
        public decimal? Ss2Grunnlagforvedtaket15 { get; set; }
        public decimal? Ss2Grunnlagforvedtaket16 { get; set; }
        public decimal? Ss2Grunnlagforvedtaket17 { get; set; }
        public string Ss2Plassering { get; set; }
        public decimal? Ss2Plassertannenkommunenr { get; set; }
        public string Ss2Hovedgrunnavsluttet { get; set; }
        public string Ss2Barnetborhos { get; set; }
        public decimal? Ss2Avsluttet { get; set; }
        public decimal? Ss2Tiltakh01 { get; set; }
        public decimal? Ss2Tiltako01 { get; set; }
        public decimal? Ss2Tiltakh02 { get; set; }
        public decimal? Ss2Tiltako02 { get; set; }
        public decimal? Ss2Tiltakh03 { get; set; }
        public decimal? Ss2Tiltako03 { get; set; }
        public decimal? Ss2Tiltakh04 { get; set; }
        public decimal? Ss2Tiltako04 { get; set; }
        public decimal? Ss2Tiltakh05 { get; set; }
        public decimal? Ss2Tiltako05 { get; set; }
        public decimal? Ss2Tiltakh06 { get; set; }
        public decimal? Ss2Tiltako06 { get; set; }
        public decimal? Ss2Tiltakh07 { get; set; }
        public decimal? Ss2Tiltako07 { get; set; }
        public decimal? Ss2Tiltakh08 { get; set; }
        public decimal? Ss2Tiltako08 { get; set; }
        public decimal? Ss2Tiltakh09 { get; set; }
        public decimal? Ss2Tiltako09 { get; set; }
        public decimal? Ss2Tiltakh10 { get; set; }
        public decimal? Ss2Tiltako10 { get; set; }
        public decimal? Ss2Tiltakh11 { get; set; }
        public decimal? Ss2Tiltako11 { get; set; }
        public decimal? Ss2Tiltakh12 { get; set; }
        public decimal? Ss2Tiltako12 { get; set; }
        public decimal? Ss2Tiltakh13 { get; set; }
        public decimal? Ss2Tiltako13 { get; set; }
        public decimal? Ss2Tiltakh14 { get; set; }
        public decimal? Ss2Tiltako14 { get; set; }
        public decimal? Ss2Tiltakh15 { get; set; }
        public decimal? Ss2Tiltako15 { get; set; }
        public decimal? Ss2Tiltakh16 { get; set; }
        public decimal? Ss2Tiltako16 { get; set; }
        public decimal? Ss2Tiltakh17 { get; set; }
        public decimal? Ss2Tiltako17 { get; set; }
        public decimal? Ss2Tiltakh18 { get; set; }
        public decimal? Ss2Tiltako18 { get; set; }
        public decimal? Ss2Tiltakh19 { get; set; }
        public decimal? Ss2Tiltako19 { get; set; }
        public decimal? Ss2Tiltakh20 { get; set; }
        public decimal? Ss2Tiltako20 { get; set; }
        public decimal? Ss2Tiltakh21 { get; set; }
        public decimal? Ss2Tiltako21 { get; set; }
        public decimal? Ss2Tiltakh22 { get; set; }
        public decimal? Ss2Tiltako22 { get; set; }
        public decimal? Ss2Tiltakh23 { get; set; }
        public decimal? Ss2Tiltako23 { get; set; }
        public decimal? Ss2Tiltakh24 { get; set; }
        public decimal? Ss2Tiltako24 { get; set; }
        public decimal? Ss2Tiltakh25 { get; set; }
        public decimal? Ss2Tiltako25 { get; set; }
        public decimal? Ss2Tiltakh26 { get; set; }
        public decimal? Ss2Tiltako26 { get; set; }
        public decimal? Ss2Tiltakh27 { get; set; }
        public decimal? Ss2Tiltako27 { get; set; }
        public decimal? Ss2Tiltakh28 { get; set; }
        public decimal? Ss2Tiltako28 { get; set; }
        public string Ss2Tiltak24typetiltakh { get; set; }
        public string Ss2Tiltak24typetiltako { get; set; }
        public string Ss2Tiltak24lovgrunnlag1 { get; set; }
        public string Ss2Tiltak24lovgrunnlag2 { get; set; }
        public string Ss2Tiltak24tidlmnd { get; set; }
        public string Ss2Tiltak24tidlar { get; set; }
        public string Ss2Tiltak24antmnd { get; set; }
        public string Ss2Tiltak25typetiltakh { get; set; }
        public string Ss2Tiltak25typetiltako { get; set; }
        public string Ss2Tiltak25lovgrunnlag1 { get; set; }
        public string Ss2Tiltak25lovgrunnlag2 { get; set; }
        public string Ss2Tiltak25tidlmnd { get; set; }
        public string Ss2Tiltak25tidlar { get; set; }
        public string Ss2Tiltak25antmnd { get; set; }
        public string Ss2Tiltak26typetiltakh { get; set; }
        public string Ss2Tiltak26typetiltako { get; set; }
        public string Ss2Tiltak26lovgrunnlag1 { get; set; }
        public string Ss2Tiltak26lovgrunnlag2 { get; set; }
        public string Ss2Tiltak26tidlmnd { get; set; }
        public string Ss2Tiltak26tidlar { get; set; }
        public string Ss2Tiltak26antmnd { get; set; }
        public string Ss2Tiltak27typetiltakh { get; set; }
        public string Ss2Tiltak27typetiltako { get; set; }
        public string Ss2Tiltak27lovgrunnlag1 { get; set; }
        public string Ss2Tiltak27lovgrunnlag2 { get; set; }
        public string Ss2Tiltak27tidlmnd { get; set; }
        public string Ss2Tiltak27tidlar { get; set; }
        public string Ss2Tiltak27antmnd { get; set; }
        public string Ss2Tiltak28typetiltakh { get; set; }
        public string Ss2Tiltak28typetiltako { get; set; }
        public string Ss2Tiltak28lovgrunnlag1 { get; set; }
        public string Ss2Tiltak28lovgrunnlag2 { get; set; }
        public string Ss2Tiltak28tidlmnd { get; set; }
        public string Ss2Tiltak28tidlar { get; set; }
        public string Ss2Tiltak28antmnd { get; set; }
        public decimal? Ss2Tiltak01tiltakihjem { get; set; }
        public decimal? Ss2Tiltak01tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak02tiltakihjem { get; set; }
        public decimal? Ss2Tiltak02tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak03tiltakihjem { get; set; }
        public decimal? Ss2Tiltak03tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak04tiltakihjem { get; set; }
        public decimal? Ss2Tiltak04tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak05tiltakihjem { get; set; }
        public decimal? Ss2Tiltak05tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak06tiltakihjem { get; set; }
        public decimal? Ss2Tiltak06tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak07tiltakihjem { get; set; }
        public decimal? Ss2Tiltak07tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak08tiltakihjem { get; set; }
        public decimal? Ss2Tiltak08tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak09tiltakihjem { get; set; }
        public decimal? Ss2Tiltak09tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak10tiltakihjem { get; set; }
        public decimal? Ss2Tiltak10tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak11tiltakihjem { get; set; }
        public decimal? Ss2Tiltak11tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak12tiltakihjem { get; set; }
        public decimal? Ss2Tiltak12tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak13tiltakihjem { get; set; }
        public decimal? Ss2Tiltak13tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak14tiltakihjem { get; set; }
        public decimal? Ss2Tiltak14tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak15tiltakihjem { get; set; }
        public decimal? Ss2Tiltak15tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak16tiltakihjem { get; set; }
        public decimal? Ss2Tiltak16tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak17tiltakihjem { get; set; }
        public decimal? Ss2Tiltak17tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak18tiltakihjem { get; set; }
        public decimal? Ss2Tiltak18tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak19tiltakihjem { get; set; }
        public decimal? Ss2Tiltak19tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak20tiltakihjem { get; set; }
        public decimal? Ss2Tiltak20tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak21tiltakihjem { get; set; }
        public decimal? Ss2Tiltak21tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak22tiltakihjem { get; set; }
        public decimal? Ss2Tiltak22tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak23tiltakihjem { get; set; }
        public decimal? Ss2Tiltak23tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak24tiltakihjem { get; set; }
        public decimal? Ss2Tiltak24tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak25tiltakihjem { get; set; }
        public decimal? Ss2Tiltak25tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak26tiltakihjem { get; set; }
        public decimal? Ss2Tiltak26tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak27tiltakihjem { get; set; }
        public decimal? Ss2Tiltak27tiltakuhjem { get; set; }
        public decimal? Ss2Tiltak28tiltakihjem { get; set; }
        public decimal? Ss2Tiltak28tiltakuhjem { get; set; }
        public decimal? Ss2Tiltakih01 { get; set; }
        public decimal? Ss2Tiltakuh01 { get; set; }
        public decimal? Ss2Tiltakih02 { get; set; }
        public decimal? Ss2Tiltakuh02 { get; set; }
        public decimal? Ss2Tiltakih03 { get; set; }
        public decimal? Ss2Tiltakuh03 { get; set; }
        public decimal? Ss2Tiltakih04 { get; set; }
        public decimal? Ss2Tiltakuh04 { get; set; }
        public decimal? Ss2Tiltakih05 { get; set; }
        public decimal? Ss2Tiltakuh05 { get; set; }
        public decimal? Ss2Tiltakih06 { get; set; }
        public decimal? Ss2Tiltakuh06 { get; set; }
        public decimal? Ss2Tiltakih07 { get; set; }
        public decimal? Ss2Tiltakuh07 { get; set; }
        public decimal? Ss2Tiltakih08 { get; set; }
        public decimal? Ss2Tiltakuh08 { get; set; }
        public decimal? Ss2Tiltakih09 { get; set; }
        public decimal? Ss2Tiltakuh09 { get; set; }
        public decimal? Ss2Tiltakih10 { get; set; }
        public decimal? Ss2Tiltakuh10 { get; set; }
        public decimal? Ss2Tiltakih11 { get; set; }
        public decimal? Ss2Tiltakuh11 { get; set; }
        public decimal? Ss2Tiltakih12 { get; set; }
        public decimal? Ss2Tiltakuh12 { get; set; }
        public decimal? Ss2Tiltakih13 { get; set; }
        public decimal? Ss2Tiltakuh13 { get; set; }
        public decimal? Ss2Tiltakih14 { get; set; }
        public decimal? Ss2Tiltakuh14 { get; set; }
        public decimal? Ss2Tiltakih15 { get; set; }
        public decimal? Ss2Tiltakuh15 { get; set; }
        public decimal? Ss2Tiltakih16 { get; set; }
        public decimal? Ss2Tiltakuh16 { get; set; }
        public decimal? Ss2Tiltakih17 { get; set; }
        public decimal? Ss2Tiltakuh17 { get; set; }
        public decimal? Ss2Tiltakih18 { get; set; }
        public decimal? Ss2Tiltakuh18 { get; set; }
        public decimal? Ss2Tiltakih19 { get; set; }
        public decimal? Ss2Tiltakuh19 { get; set; }
        public decimal? Ss2Tiltakih20 { get; set; }
        public decimal? Ss2Tiltakuh20 { get; set; }
        public decimal? Ss2Tiltakih21 { get; set; }
        public decimal? Ss2Tiltakuh21 { get; set; }
        public decimal? Ss2Tiltakih22 { get; set; }
        public decimal? Ss2Tiltakuh22 { get; set; }
        public decimal? Ss2Tiltakih23 { get; set; }
        public decimal? Ss2Tiltakuh23 { get; set; }
        public decimal? Ss2Tiltakih24 { get; set; }
        public decimal? Ss2Tiltakuh24 { get; set; }
        public decimal? Ss2Tiltakih25 { get; set; }
        public decimal? Ss2Tiltakuh25 { get; set; }
        public decimal? Ss2Tiltakih26 { get; set; }
        public decimal? Ss2Tiltakuh26 { get; set; }
        public decimal? Ss2Tiltakih27 { get; set; }
        public decimal? Ss2Tiltakuh27 { get; set; }
        public decimal? Ss2Tiltakih28 { get; set; }
        public decimal? Ss2Tiltakuh28 { get; set; }
        public string Ss2Vedtak1Nr { get; set; }
        public string Ss2Vedtak1Type { get; set; }
        public string Ss2Vedtak1Varighet { get; set; }
        public string Ss2Vedtak2Nr { get; set; }
        public string Ss2Vedtak2Type { get; set; }
        public string Ss2Vedtak2Varighet { get; set; }
        public string Ss2Vedtak3Nr { get; set; }
        public string Ss2Vedtak3Type { get; set; }
        public string Ss2Vedtak3Varighet { get; set; }
        public string Ss2Vedtak4Nr { get; set; }
        public string Ss2Vedtak4Type { get; set; }
        public string Ss2Vedtak4Varighet { get; set; }
        public string Ss2Vedtak5Nr { get; set; }
        public string Ss2Vedtak5Type { get; set; }
        public string Ss2Vedtak5Varighet { get; set; }
        public string Ss2Vedtak6Nr { get; set; }
        public string Ss2Vedtak6Type { get; set; }
        public string Ss2Vedtak6Varighet { get; set; }
        public string Ss2Vedtak7Nr { get; set; }
        public string Ss2Vedtak7Type { get; set; }
        public string Ss2Vedtak7Varighet { get; set; }
        public string Ss2UtilsiktetFlytting { get; set; }
        public decimal? Ss2Tiltaksplan { get; set; }

        public virtual FaStatSsb1 FaStatSsb1 { get; set; }
    }
}
