using System;

namespace UttrekkFamilia.Models
{
    public partial class FaStatFylkesmann2sum
    {
        public DateTime Sf2PeriodeFradato { get; set; }
        public string DisDistriktskode { get; set; }
        public decimal? Sf2P11A { get; set; }
        public decimal? Sf2P11B { get; set; }
        public decimal? Sf2P11C { get; set; }
        public decimal? Sf2P11D { get; set; }
        public decimal? Sf2P2A { get; set; }
        public decimal? Sf2P2B { get; set; }
        public decimal? Sf2P2C { get; set; }
        public decimal? Sf2P2D { get; set; }
        public decimal? Sf2P2E { get; set; }
        public decimal? Sf2P2EHerav { get; set; }
        public decimal? Sf2P2F { get; set; }
        public decimal? Sf2P2G { get; set; }
        public decimal? Sf2P2GHerav { get; set; }
        public decimal? Sf2P2H { get; set; }
        public decimal? Sf2P3 { get; set; }
        public decimal? Sf2P3A { get; set; }
        public decimal? Sf2P3B { get; set; }
        public decimal? Sf2P3C { get; set; }
        public decimal? Sf2P3D { get; set; }
        public decimal? Sf2P3E { get; set; }
        public decimal? Sf2P3F { get; set; }
        public decimal? Sf2P3G { get; set; }
        public decimal? Sf2P3AntallUtvidet { get; set; }
        public decimal? Sf2P4A { get; set; }
        public decimal? Sf2P4AHerav { get; set; }
        public decimal? Sf2P4ATtp { get; set; }
        public decimal? Sf2P4A445 { get; set; }
        public decimal? Sf2P4A445Herav { get; set; }
        public decimal? Sf2P4B { get; set; }
        public decimal? Sf2P4BHerav { get; set; }
        public decimal? Sf2P4C { get; set; }
        public decimal? Sf2P4CHerav { get; set; }
        public decimal? Sf2P4D { get; set; }
        public decimal? Sf2P4DHerav { get; set; }
        public decimal? Sf2P4DInstitusjon { get; set; }
        public decimal? Sf2P4D424 { get; set; }
        public decimal? Sf2P4D426 { get; set; }
        public decimal? Sf2P4DFosterhjem { get; set; }
        public decimal? Sf2P4D427 { get; set; }
        public decimal? Sf2P4E { get; set; }
        public decimal? Sf2P4EHalvaar { get; set; }
        public decimal? Sf2P4F { get; set; }
        public decimal? Sf2P4FHalvaar { get; set; }
        public decimal? Sf2P4G { get; set; }
        public decimal? Sf2P4GHalvaar { get; set; }
        public decimal? Sf2P4H { get; set; }
        public decimal? Sf2P4HHalvaar { get; set; }
        public decimal? Sf2P4I { get; set; }
        public decimal? Sf2P4IHalvaar { get; set; }
        public decimal? Sf2P4J { get; set; }
        public decimal? Sf2P4JHalvaar { get; set; }
        public decimal? Sf2P4K { get; set; }
        public decimal? Sf2P51 { get; set; }
        public decimal? Sf2P51U18 { get; set; }
        public decimal? Sf2P52 { get; set; }
        public decimal? Sf2P52Tilsynsfoerer { get; set; }
        public decimal? Sf2P521 { get; set; }
        public decimal? Sf2P522 { get; set; }
        public decimal? Sf2P523 { get; set; }
        public decimal? Sf2P524 { get; set; }
        public decimal? Sf2P5FosterhjEgenkom { get; set; }
        public decimal? Sf2P5FosterhjAnnenkom { get; set; }
        public decimal? Sf2P618SisteHalvaar { get; set; }
        public decimal? Sf2P6HeravEgetOenske { get; set; }
        public decimal? Sf2P6HeravAvslag { get; set; }
        public decimal? Sf2P6HeravAnnetOenske { get; set; }
        public decimal? Sf2P7A { get; set; }
        public decimal? Sf2P7B { get; set; }
        public decimal? Sf2P7C { get; set; }
        public decimal? Sf2P7CHerav { get; set; }
        public decimal? Sf2P7D { get; set; }
        public decimal? Sf2P7Bortfalt462 { get; set; }
        public decimal? Sf2P7Bortfalt4252 { get; set; }
        public decimal? Sf2P7Bortfalt4132 { get; set; }
        public string Sf2P8A { get; set; }
        public string Sf2P8B { get; set; }
        public string Sf2P8C { get; set; }
        public string Sf2P8Kommentar { get; set; }
        public string Sf2Kontaktperson { get; set; }
        public string Sf2Epost { get; set; }
        public decimal? Sf2Kommunenr { get; set; }
        public string Sf2Kommune { get; set; }
        public string Sf2Etat { get; set; }
        public string Sf2Adresse1 { get; set; }
        public string Sf2Adresse2 { get; set; }
        public string Sf2Tlf { get; set; }
        public string Sf2Postnr { get; set; }
        public string Sf2Poststed { get; set; }
        public decimal? Sf2P4E2 { get; set; }
        public decimal? Sf2P4E2Halvaar { get; set; }
        public decimal? Sf2P522Oppf { get; set; }
        public decimal? Sf2P524Oppf { get; set; }
        public decimal? Sf2P5OppfKtrlAnsv { get; set; }
        public decimal? Sf2P5OppfKtrlAnsvOvr1 { get; set; }
        public decimal? Sf2P5OppfKtrlAnsvUndr1 { get; set; }
        public string Sf2Fylke { get; set; }
        public decimal? Sf2Iksamarbeid { get; set; }
        public decimal? Sf2BvtjenesteTilsyn { get; set; }
        public string Sf2Ikkommuner { get; set; }
        public string Sf2Tilsynsansvar { get; set; }
        public decimal? Sf2P11E { get; set; }
        public decimal? Sf2P11F { get; set; }
        public decimal? Sf2P11G { get; set; }
        public decimal? Sf2P11H { get; set; }
        public decimal? Sf2P31 { get; set; }
        public decimal? Sf2P4A442 { get; set; }
        public decimal? Sf2P4A442Herav { get; set; }
        public decimal? Sf2P4A446 { get; set; }
        public decimal? Sf2P4A446Herav { get; set; }
        public decimal? Sf2P4A44Ttp { get; set; }
        public decimal? Sf2P4A44TtpHerav { get; set; }
        public decimal? Sf2P4KHalvaar { get; set; }
        public decimal? Sf2P4L { get; set; }
        public decimal? Sf2P4M { get; set; }
        public decimal? Sf2P4MHalvaar { get; set; }
        public decimal? Sf2P4N { get; set; }
        public decimal? Sf2P4NHalvaar { get; set; }
        public decimal? Sf2P2E2Overfrist { get; set; }
        public decimal? Sf2P2E3Prosentoverfrist { get; set; }
        public decimal? Sf2P2I { get; set; }
        public decimal? Sf2P2J { get; set; }
    }
}
